# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_messageuser_touser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_messagesenduser',
            name='massage',
            field=models.TextField(default='', max_length=3050),
        ),
    ]
