# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0004_auto_20170122_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_correspondents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='\u041e\u0431\u0449\u0435\u043d\u0438\u0435', max_length=250)),
                ('massage', models.TextField(default='', max_length=3050)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to=settings.AUTH_USER_MODEL)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='message_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser_2', to=settings.AUTH_USER_MODEL)),
                ('toCorrespondents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser_2', to='message.message_correspondents')),
            ],
        ),
        migrations.RemoveField(
            model_name='message_messagesenduser',
            name='fromUser',
        ),
        migrations.RemoveField(
            model_name='message_messagesenduser',
            name='toUser',
        ),
        migrations.RemoveField(
            model_name='message_senduser',
            name='fromUser',
        ),
        migrations.RemoveField(
            model_name='message_senduser',
            name='toUser',
        ),
        migrations.DeleteModel(
            name='message_messageSendUser',
        ),
        migrations.DeleteModel(
            name='message_sendUser',
        ),
    ]
