# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0006_message_messageuser_tocorrespondents'),
    ]

    operations = [
        migrations.CreateModel(
            name='massege_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='\u041e\u0431\u0449\u0435\u043d\u0438\u0435', max_length=250)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='message_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField(default='', max_length=3050)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('correspondents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondents_message_message', to='message.massege_user')),
            ],
        ),
        migrations.RemoveField(
            model_name='message_correspondents',
            name='fromUser',
        ),
        migrations.RemoveField(
            model_name='message_correspondents',
            name='toUser',
        ),
        migrations.RemoveField(
            model_name='message_messageuser',
            name='fromUser',
        ),
        migrations.RemoveField(
            model_name='message_messageuser',
            name='toCorrespondents',
        ),
        migrations.RemoveField(
            model_name='message_messageuser',
            name='toUser',
        ),
        migrations.RemoveField(
            model_name='message_user',
            name='fromUser',
        ),
        migrations.RemoveField(
            model_name='message_user',
            name='toCorrespondents',
        ),
        migrations.DeleteModel(
            name='message_correspondents',
        ),
        migrations.DeleteModel(
            name='message_messageUser',
        ),
        migrations.DeleteModel(
            name='message_user',
        ),
    ]
