# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0007_auto_20170122_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massege_user',
            name='user_one',
        ),
        migrations.AddField(
            model_name='massege_user',
            name='user_one',
            field=models.ManyToManyField(related_name='user_one', to=settings.AUTH_USER_MODEL),
        ),
    ]
