# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20170122_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massege_user',
            name='user_two',
        ),
    ]
