# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newMatrix', '0005_auto_20170118_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmatrix_smalldesk',
            name='smallDesk_3',
        ),
        migrations.AlterField(
            model_name='newmatrix_smalldesk',
            name='smallDesk_2',
            field=models.PositiveIntegerField(default=19),
        ),
    ]
