# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newMatrix', '0006_auto_20170118_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmatrix_smalldesk',
            name='smallDesk_2',
            field=models.PositiveIntegerField(default=21),
        ),
    ]
