# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('newMatrix', '0008_auto_20170118_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmatrix_smalldesk',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='newmatrix_smalldesk',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Type'),
        ),
    ]
