# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('newMatrix', '0009_auto_20170118_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmatrix_smalldesk',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='newmatrix_smalldesk',
            name='item_type',
        ),
        migrations.AddField(
            model_name='newmatrix_smalldesk',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='newmatrix_smalldesk',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='newmatrix_smalldesk',
            name='tag',
            field=models.SlugField(default=19),
        ),
    ]
