# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newMatrix', '0015_auto_20170118_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='newMatix_largeDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='newMatrix_freePlaceSmallDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeSpaceSmallDesk_freePlace', models.IntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='newmatrix_smalldesk',
            name='smallDesk_3',
            field=models.OneToOneField(blank=True, default=19, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smallDesk_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newmatrix_smalldesk',
            name='smallDesk_2',
            field=models.OneToOneField(blank=True, default=19, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smallDesk_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newmatrix_freeplacesmalldesk',
            name='freeSpaceSmallDesk_smallDesk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newMatrix.newMatrix_smallDesk', unique=True),
        ),
        migrations.AddField(
            model_name='newmatix_largedesk',
            name='largeDesk_OneDesk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='largeDeskOneDesk', to='newMatrix.newMatrix_smallDesk'),
        ),
        migrations.AddField(
            model_name='newmatix_largedesk',
            name='largeDesk_TwoDesk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='largeDeskTwoDesk', to='newMatrix.newMatrix_smallDesk'),
        ),
        migrations.AddField(
            model_name='newmatix_largedesk',
            name='largeDesk_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='largeDesk_User', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
