# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newMatrix', '0016_auto_20170118_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmatix_largedesk',
            name='largeDesk_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='largeDesk_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newmatrix_freeplacesmalldesk',
            name='freeSpaceSmallDesk_smallDesk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newMatrix.newMatrix_smallDesk'),
        ),
    ]
