# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newMatrix', '0017_auto_20170118_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newmatix_largedesk',
            old_name='largeDesk_TwoDesk',
            new_name='largeDesk_LeftDesk',
        ),
        migrations.RenameField(
            model_name='newmatix_largedesk',
            old_name='largeDesk_OneDesk',
            new_name='largeDesk_RightDesk',
        ),
    ]
