# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newMatrix', '0020_newmatrix_userdesk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmatrix_smalldesk',
            name='smallDesk_LeftPlace',
            field=models.ForeignKey(blank=True, default=19, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smallDesk_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newmatrix_smalldesk',
            name='smallDesk_RightPlace',
            field=models.ForeignKey(blank=True, default=19, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smallDesk_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
