# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newMatrix', '0021_auto_20170118_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmatrix_smalldesk',
            name='smallDesk_UserInHead',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, related_name='smallDesk_1', to=settings.AUTH_USER_MODEL),
        ),
    ]
