# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newMatrix', '0024_auto_20170118_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='newMatrix_UserLargeDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserDesk_Desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserLargeDesk_Desk', to='newMatrix.newMatix_largeDesk')),
                ('UserDesk_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserLargeDesk_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
