# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newMatrix', '0025_newmatrix_userlargedesk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newmatrix_userlargedesk',
            old_name='UserDesk_Desk',
            new_name='UserLargeDesk_Desk',
        ),
        migrations.RenameField(
            model_name='newmatrix_userlargedesk',
            old_name='UserDesk_User',
            new_name='UserLargeDesk_User',
        ),
    ]
