# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newMatrix', '0027_newmatrix_largedesksmalldesk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newmatrix_largedesksmalldesk',
            old_name='UserLargeDesk_Desk',
            new_name='LargeDeskSmallDesk_LargeDesk',
        ),
        migrations.RenameField(
            model_name='newmatrix_largedesksmalldesk',
            old_name='UserLargeDesk_User',
            new_name='LargeDeskSmallDesk_SmallDesk',
        ),
    ]
