# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0006_auto_20170210_1756'),
        ('newMatrix', '0030_auto_20170120_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixMoneyPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inMatrix', models.PositiveIntegerField(default=1000)),
                ('outMatrix', models.PositiveIntegerField(default=1500)),
                ('tovarMatrix', models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='MatrixMoneyPay_tovarMatrix', to='tovar.Product')),
            ],
        ),
        migrations.AddField(
            model_name='newmatrix_smalldesk',
            name='smallDesk_matrixMoneyPay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='smallDesk_matrixMoneyPay', to='newMatrix.MatrixMoneyPay'),
        ),
    ]
