# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passWallet',
            field=models.CharField(default=b'qqqqqqqqq', max_length=16, verbose_name='\u0424\u0438\u043d\u0430\u043d\u0441\u043e\u0432\u044b\u0439 \u043f\u0430\u0440\u043e\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1000, upload_to=b'static/accounts/avatar/%Y/%m/', verbose_name='avatar'),
        ),
    ]
