# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170110_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passWallet',
            field=models.CharField(default=b'qqqqqqqqq', max_length=16, verbose_name='passWallet'),
        ),
    ]
