# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170110_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passWallet',
            field=models.CharField(blank=True, max_length=16, verbose_name='passWallet'),
        ),
    ]
