# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170110_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.TextField(max_length=100, null=True, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=24, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, verbose_name='phone_number'),
        ),
    ]
