# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170110_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='adress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passWallet',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='passWallet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='phone_number'),
        ),
    ]
