# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170110_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
