# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170112_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 12, 17, 38, 40, 618000), null=True),
        ),
    ]
