# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20170112_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passWallet',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='passWallet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 12, 19, 56, 19, 12000), null=True),
        ),
    ]
