# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170112_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 12, 20, 25, 53, 942000), null=True),
        ),
    ]
