# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20170113_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 13, 13, 46, 7, 938000), null=True),
        ),
    ]
