# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20170114_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 14, 22, 28, 30, 180000), null=True),
        ),
    ]
