# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20170115_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 15, 14, 3, 45, 750000), null=True),
        ),
    ]
