# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20170115_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 15, 14, 15, 20, 959000), null=True),
        ),
    ]
