# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20170115_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1000, upload_to=b'static/accounts/avatar/%Y/%m/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 15, 20, 50, 41, 788000), null=True),
        ),
    ]
