# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20170115_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 16, 7, 21, 50, 671000), null=True),
        ),
    ]
