# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 11:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20170116_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 16, 14, 5, 4, 243000), null=True),
        ),
    ]
