# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_auto_20170118_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 18, 19, 56, 9, 516000), null=True),
        ),
    ]
