# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_auto_20170118_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 19, 10, 18, 15, 343000), null=True),
        ),
    ]
