# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 23:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_auto_20170120_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_is_structure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 20, 2, 29, 5, 945000), null=True),
        ),
    ]
