# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_auto_20170120_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 22, 11, 21, 9, 624000), null=True),
        ),
    ]
