# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_auto_20170122_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 22, 13, 13, 47, 654000), null=True),
        ),
    ]
