# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_auto_20170122_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 22, 15, 20, 32, 568000), null=True),
        ),
    ]
