# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_auto_20170122_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 22, 18, 22, 56, 48000), null=True),
        ),
    ]
