# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_auto_20170122_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 5, 17, 56, 48, 837000), null=True),
        ),
    ]
