# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_auto_20170205_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 5, 23, 44, 28, 301000), null=True),
        ),
    ]
