# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_auto_20170205_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 9, 14, 46, 57, 966000), null=True),
        ),
    ]
