# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_auto_20170209_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 9, 23, 32, 46, 55000), null=True),
        ),
    ]
