# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_auto_20170210_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 10, 21, 42, 24, 661000), null=True),
        ),
    ]
