# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 11:03
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_HistoryTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HistoryTransfer_userGets', models.IntegerField(verbose_name=accounts.models.User)),
                ('HistoryTransfer_TransferAmount', models.IntegerField(default=0)),
                ('HistoryTransfer_userTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
