# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_historytransfer',
            name='HistoryTransfer_userGets',
            field=models.IntegerField(),
        ),
    ]
