# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.IntegerField(default=1)),
                ('parent', models.IntegerField(default=1)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMoneyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.IntegerField(default=1)),
                ('moneyprof', models.IntegerField(default=1000)),
                ('createuser', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.IntegerField(default=1)),
                ('parent', models.IntegerField(default=1)),
                ('createuser', models.IntegerField(default=1)),
            ],
        ),
    ]
