# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0002_auto_20170109_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwallet',
            name='prof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilemoneymodel',
            name='prof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
