# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0003_auto_20170110_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InfoProduct_name', models.CharField(max_length=50)),
                ('InfoProduct_title', models.CharField(max_length=250)),
                ('InfoProduct_text', models.TextField(max_length=1050)),
                ('InfoProduct_price', models.IntegerField(max_length=1050)),
            ],
        ),
    ]
