# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0004_infoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduct',
            name='InfoProduct_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='InfoProduct_price',
            field=models.IntegerField(default=0),
        ),
    ]
