# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0006_auto_20170112_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproduct',
            name='InfoProduct_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
