# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0007_auto_20170112_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemoneymodel',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='profileusermodel',
            name='prof',
        ),
        migrations.RenameField(
            model_name='modelwallet',
            old_name='password',
            new_name='ModelWallet_password',
        ),
        migrations.RenameField(
            model_name='modelwallet',
            old_name='prof',
            new_name='ModelWallet_user',
        ),
        migrations.RenameField(
            model_name='modelwallet',
            old_name='parent',
            new_name='ModelWallet_walletPrice',
        ),
        migrations.AddField(
            model_name='modelwallet',
            name='ModelWallet_dateCreate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelwallet',
            name='ModelWallet_infoProduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logsys.InfoProduct'),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='InfoProduct_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProfileMoneyModel',
        ),
        migrations.DeleteModel(
            name='ProfileUserModel',
        ),
    ]
