# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logsys', '0009_remove_modelwallet_modelwallet_infoproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserWallet_walletPrice', models.IntegerField(default=1)),
                ('UserWallet_password', models.CharField(max_length=50)),
                ('UserWallet_dateCreate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UserWallet_IsActive', models.BooleanField(default=False)),
                ('UserWallet_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='modelwallet',
            name='ModelWallet_user',
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='InfoProduct_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='ModelWallet',
        ),
    ]
