# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0010_auto_20170112_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='UserWallet_walletPrice',
            field=models.IntegerField(default=0),
        ),
    ]
