# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0011_auto_20170112_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='UserWallet_walletBonuce',
            field=models.IntegerField(default=0),
        ),
    ]
