# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0012_userwallet_userwallet_walletbonuce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoProduct',
        ),
    ]
