# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tovar', '0003_auto_20170209_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderPaymentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 9, 23, 32, 46, 137000), null=True),
        ),
        migrations.AddField(
            model_name='orderpaymentproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderPaymentProduct_product', to='tovar.OrderProduct'),
        ),
        migrations.AddField(
            model_name='orderpaymentproduct',
            name='userPayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderPaymentProduct_userPayment', to=settings.AUTH_USER_MODEL),
        ),
    ]
