# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0004_auto_20170209_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 9, 23, 34, 4, 792000), null=True),
        ),
    ]
